export const dummyData: dummy[] = [
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar:
      "https://images.unsplash.com/photo-1511485977113-f34c92461ad9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&fit=crop&h=200&w=200&ixid=eyJhcHBfaWQiOjE3Nzg0fQ",
    name: "Martiana dialan",
    title: "Product designer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    name: "Micheal colorand",
    title: "Software engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Brown Luis",
    title: "Full stack engineer",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Lysa sandiago",
    title: "Head of designers",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesettin industry.",
    linkedin: "https://www.linkedin.com/in/dummy-link-775982111/",
    twitter: "https://t.co/nZWSU4WqpO",
  },
];
